import Link from "next/link";
import LabGate from "@/components/lab/LabGate";
import AuditWizard from "@/components/lab/AuditWizard";

export const metadata = {
  title: "Automation Opportunity Finder — Darbury AI Tools",
  description:
    "Five questions about your workflow. Three specific automation opportunities — generated for your situation, not a generic checklist.",
};

export default function AutomationFinderPage() {
  return (
    <main className="pt-24 pb-24 px-6 max-w-5xl mx-auto">
      {/* Breadcrumb */}
      <p className="font-[var(--font-jetbrains)] text-xs text-[var(--text-muted)] mb-10">
        <Link href="/lab" className="hover:text-[var(--accent-teal)] transition-colors">
          AI Tools
        </Link>
        {" / "}
        <span className="text-[var(--text-secondary)]">Automation Opportunity Finder</span>
      </p>

      {/* Page header */}
      <p className="font-[var(--font-jetbrains)] text-xs text-[var(--accent-teal)] uppercase tracking-[0.25em] mb-4">
        AI Tool 3
      </p>
      <h1 className="font-[var(--font-barlow)] font-bold text-5xl md:text-6xl uppercase tracking-tight text-[var(--text-primary)] mb-4">
        Automation Opportunity Finder
      </h1>
      <p className="text-xl text-[var(--text-secondary)] max-w-2xl mb-3">
        Five questions about your workflow. Three specific opportunities to save time, reduce
        errors, and deliver faster — generated for your situation, not a generic checklist.
      </p>
      <div className="flex flex-wrap gap-6 mb-16">
        <p className="text-sm text-[var(--text-muted)]">Takes about 3 minutes.</p>
        <p className="text-sm text-[var(--text-muted)]">
          Your report is generated by AI and reviewed by Dave. If any opportunities resonate, a
          conversation is the natural next step.
        </p>
      </div>

      {/* Lab gate wraps the tool — verified users see AuditWizard directly */}
      <LabGate>
        <AuditWizard />
      </LabGate>
    </main>
  );
}
