"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import Button from "@/components/ui/Button";

interface Opportunity {
  title: string;
  description: string;
  impact: string;
}

export interface ReportResult {
  report: {
    reportTitle: string;
    intro: string;
    opportunities: [Opportunity, Opportunity, Opportunity];
    closing: string;
  };
  submissionId: string;
  userName: string;
  userCompany: string;
  userEmail: string;
  visitorEmailSent: boolean;
  date: string;
}

function buildCopyText(r: ReportResult): string {
  const { report, userName, userCompany, date } = r;
  const company = userCompany || "Your Team";
  const lines = [
    `3 AUTOMATION OPPORTUNITIES FOR ${company.toUpperCase()}`,
    `Prepared for ${userName} — ${date}`,
    `Generated by Darbury AI Lab — darbury.com`,
    ``,
    report.intro,
    ``,
    ...report.opportunities.flatMap((o, i) => [
      `OPPORTUNITY ${i + 1}: ${o.title}`,
      o.description,
      `Impact: ${o.impact}`,
      ``,
    ]),
    report.closing,
    ``,
    `——`,
    `Darbury Ltd — Engineering Technology Consultancy`,
    `Contact Dave: darbury.com/contact`,
  ];
  return lines.join("\n");
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback: select a hidden textarea
      const el = document.createElement("textarea");
      el.value = text;
      el.style.position = "fixed";
      el.style.opacity = "0";
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  }

  return (
    <button
      type="button"
      onClick={handleCopy}
      className={[
        "inline-flex items-center gap-2 px-5 py-2.5 rounded border text-sm font-[var(--font-barlow)] font-semibold uppercase tracking-wider transition-all duration-200",
        copied
          ? "border-[var(--accent-teal)] bg-[var(--accent-teal)]/10 text-[var(--accent-teal)]"
          : "border-[var(--border)] text-[var(--text-secondary)] hover:border-[var(--accent-teal)]/50 hover:text-[var(--text-primary)]",
      ].join(" ")}
    >
      {copied ? (
        <>
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
          </svg>
          Copied
        </>
      ) : (
        <>
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={1.5}
              d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3"
            />
          </svg>
          Copy Report
        </>
      )}
    </button>
  );
}

export default function ReportCard({ data }: { data: ReportResult }) {
  const { report, userName, userCompany, userEmail, visitorEmailSent, date } = data;

  return (
    <motion.div
      initial={{ opacity: 0, y: 28 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: "easeOut" }}
      className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg overflow-hidden"
    >
      {/* Report header */}
      <div className="px-8 pt-8 pb-6 border-b border-[var(--border)]">
        <p className="font-[var(--font-jetbrains)] text-xs text-[var(--accent-teal)] uppercase tracking-[0.2em] mb-2">
          Your Report
        </p>
        <h2 className="font-[var(--font-barlow)] font-bold text-2xl md:text-3xl uppercase tracking-wide text-[var(--text-primary)] mb-1">
          {report.reportTitle}
        </h2>
        <p className="text-sm text-[var(--text-muted)] font-[var(--font-jetbrains)]">
          Prepared for {userName} · {date}
        </p>
      </div>

      {/* Intro */}
      <div className="px-8 py-6 border-b border-[var(--border)]">
        <p className="text-[var(--text-secondary)] leading-relaxed">{report.intro}</p>
      </div>

      {/* Opportunities */}
      <div className="px-8 py-6 space-y-6 border-b border-[var(--border)]">
        {report.opportunities.map((opp, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, x: -12 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.4, delay: 0.15 + i * 0.1, ease: "easeOut" }}
            className="border-l-2 border-[var(--accent-teal)] pl-5"
          >
            <p className="font-[var(--font-jetbrains)] text-xs text-[var(--text-muted)] uppercase tracking-[0.15em] mb-1">
              Opportunity {i + 1}
            </p>
            <h3 className="font-[var(--font-barlow)] font-semibold text-lg uppercase tracking-wide text-[var(--text-primary)] mb-2">
              {opp.title}
            </h3>
            <p className="text-[var(--text-secondary)] leading-relaxed text-sm mb-3">
              {opp.description}
            </p>
            <p className="text-[var(--accent-teal)] text-sm font-medium">
              → {opp.impact}
            </p>
          </motion.div>
        ))}
      </div>

      {/* Closing */}
      <div className="px-8 py-6 border-b border-[var(--border)]">
        <p className="text-[var(--text-secondary)] leading-relaxed text-sm italic">
          {report.closing}
        </p>
      </div>

      {/* Footer: copy + CTA + email confirmation */}
      <div className="px-8 py-6 flex flex-col gap-5">
        <div className="flex flex-wrap gap-3">
          <CopyButton text={buildCopyText(data)} />
          <Button href="/contact" variant="outline">
            Contact Dave →
          </Button>
        </div>

        {visitorEmailSent && (
          <p className="text-xs text-[var(--text-muted)] font-[var(--font-jetbrains)]">
            A copy of this report has been sent to{" "}
            <span className="text-[var(--text-secondary)]">{userEmail}</span>
          </p>
        )}
      </div>
    </motion.div>
  );
}
